spring:
  batch:
    job:
      enabled: false
  datasource:
      url: jdbc:mysql://stg-inflca-dumy-1030-cluster.cluster-clbbpb8kngah.ap-northeast-2.rds.amazonaws.com:3306/inflca
      username: chan
      password: chan4796
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: batch.domain
  mapper-locations: classpath:/sql/*.xml
logging:
  level:
    jdbc:
      audit: OFF # JDBC 트러블슈팅 경우를 제외하고는 사용 권장 X
      resultset: OFF # ResultSet을 포함한 모든 JDBC 호출 정보를 출력
      resultsettable: INFO  #SQL 결과 데이터 Table형식으로 출력
      sqlonly: OFF     #SQL만 로그만 출력
      sqltiming: INFO    #SQL + 소요시간 출력
      connection: OFF  # 커넥션 연결/종료 정보 출력
server:
  port: 8082